package life.majiang.community.demo.mapper;

import life.majiang.community.demo.dto.QuestionQueryDTO;
import life.majiang.community.demo.model.Question;
import life.majiang.community.demo.model.QuestionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Thu Nov 28 21:27:49 CST 2019
     */
    int invCount(Question record);
    int invCoummentCount(Question record);
    List<Question> selectRelated(Question record);
    Integer countBySearch(QuestionQueryDTO questionQueryDTO);

    List<Question> selectBySearch(QuestionQueryDTO questionQueryDTO);
}